export const CLICKHOUSE_KEYWORDS = [
  // DDL
  "CREATE",
  "DROP",
  "ALTER",
  "RENAME",
  "TRUNCATE",
  "ATTACH",
  "DETACH",
  "EXISTS",
  "IF",
  "NOT",
  "TEMPORARY",
  "MATERIALIZED",

  // DML
  "SELECT",
  "INSERT",
  "UPDATE",
  "DELETE",
  "REPLACE",
  "OPTIMIZE",
  "VALUES",
  "SET",

  // Query Structure
  "FROM",
  "WHERE",
  "GROUP",
  "BY",
  "HAVING",
  "ORDER",
  "LIMIT",
  "OFFSET",
  "UNION",
  "ALL",
  "DISTINCT",
  "TOP",
  "WITH",
  "RECURSIVE",

  // Joins
  "JOIN",
  "INNER",
  "LEFT",
  "RIGHT",
  "FULL",
  "CROSS",
  "OUTER",
  "ANY",
  "ALL",
  "ASOF",
  "ARRAY",
  "GLOBAL",
  "LOCAL",

  // ClickHouse Specific
  "PREWHERE",
  "FINAL",
  "SAMPLE",
  "FORMAT",
  "INTO",
  "OUTFILE",
  "SETTINGS",
  "ENGINE",
  "PARTITION",
  "PRIMARY",
  "KEY",
  "TTL",
  "CODEC",
  "COMPRESSION",
  "ROLLUP",
  "CUBE",
  "TOTALS",

  // Window Functions
  "WINDOW",
  "OVER",
  "PARTITION",
  "ROWS",
  "RANGE",
  "UNBOUNDED",
  "PRECEDING",
  "FOLLOWING",
  "CURRENT",
  "ROW",

  // Data Types
  "Int8",
  "Int16",
  "Int32",
  "Int64",
  "UInt8",
  "UInt16",
  "UInt32",
  "UInt64",
  "Float32",
  "Float64",
  "Decimal",
  "Decimal32",
  "Decimal64",
  "Decimal128",
  "Bool",
  "String",
  "FixedString",
  "UUID",
  "Date",
  "Date32",
  "DateTime",
  "DateTime64",
  "Array",
  "Tuple",
  "Map",
  "Nested",
  "Nullable",
  "LowCardinality",
  "Enum8",
  "Enum16",
  "IPv4",
  "IPv6",
  "Point",
  "Ring",
  "Polygon",
  "MultiPolygon",

  // Logical
  "AND",
  "OR",
  "NOT",
  "IN",
  "LIKE",
  "ILIKE",
  "REGEXP",
  "BETWEEN",
  "IS",
  "NULL",
  "TRUE",
  "FALSE",

  // Case
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",

  // Others
  "AS",
  "ASC",
  "DESC",
  "COLLATE",
  "DEFAULT",
  "COMMENT",
  "USING",
];

export const CLICKHOUSE_FUNCTIONS = [
  // Aggregate Functions
  "count",
  "sum",
  "avg",
  "min",
  "max",
  "any",
  "anyLast",
  "anyHeavy",
  "groupArray",
  "groupUniqArray",
  "topK",
  "topKWeighted",
  "uniq",
  "uniqExact",
  "uniqHLL12",
  "uniqCombined",
  "uniqCombined64",
  "quantile",
  "quantiles",
  "quantileExact",
  "quantileTiming",
  "quantileTDigest",
  "median",
  "stddevPop",
  "stddevSamp",
  "varPop",
  "varSamp",

  // Date/Time Functions
  "now",
  "today",
  "yesterday",
  "timeSlot",
  "timeSlots",
  "toDateTime",
  "toDate",
  "toUnixTimestamp",
  "fromUnixTimestamp",
  "formatDateTime",
  "parseDateTime32BestEffort",
  "parseDateTimeBestEffort",
  "addDays",
  "addWeeks",
  "addMonths",
  "addQuarters",
  "addYears",
  "subtractDays",
  "subtractWeeks",
  "subtractMonths",
  "subtractQuarters",
  "subtractYears",
  "dateDiff",
  "age",
  "toRelativeYearNum",
  "toRelativeQuarterNum",
  "toRelativeMonthNum",
  "toRelativeWeekNum",
  "toRelativeDayNum",
  "toStartOfYear",
  "toStartOfQuarter",
  "toStartOfMonth",
  "toStartOfWeek",
  "toStartOfDay",
  "toStartOfHour",
  "toStartOfMinute",
  "toStartOfFiveMinute",
  "toStartOfTenMinutes",
  "toStartOfFifteenMinutes",
  "toYear",
  "toQuarter",
  "toMonth",
  "toDayOfMonth",
  "toDayOfWeek",
  "toHour",
  "toMinute",
  "toSecond",
  "toYYYYMM",
  "toYYYYMMDD",
  "toYYYYMMDDhhmmss",

  // String Functions
  "length",
  "lengthUTF8",
  "empty",
  "notEmpty",
  "lower",
  "upper",
  "reverse",
  "concat",
  "substring",
  "substringUTF8",
  "position",
  "positionUTF8",
  "match",
  "extract",
  "extractAll",
  "like",
  "notLike",
  "ilike",
  "replace",
  "replaceAll",
  "replaceOne",
  "replaceRegexpAll",
  "replaceRegexpOne",
  "trim",
  "trimLeft",
  "trimRight",
  "trimBoth",
  "ltrim",
  "rtrim",
  "splitByChar",
  "splitByString",
  "splitByRegexp",
  "arrayStringConcat",
  "alphaTokens",
  "extractAllGroups",
  "regexpQuoteMeta",

  // Array Functions
  "array",
  "arrayJoin",
  "arrayElement",
  "arraySlice",
  "arrayPushBack",
  "arrayPushFront",
  "arrayPopBack",
  "arrayPopFront",
  "arrayConcat",
  "arraySort",
  "arraySortReverse",
  "arrayUniq",
  "arrayDistinct",
  "arrayEnumerate",
  "arrayEnumerateUniq",
  "arrayEnumerateDense",
  "arrayReverse",
  "arrayFlatten",
  "arrayCompact",
  "arrayZip",
  "has",
  "hasAll",
  "hasAny",
  "indexOf",
  "countEqual",
  "arrayCount",
  "arraySum",
  "arrayAvg",
  "arrayMax",
  "arrayMin",
  "arrayFirst",
  "arrayFirstIndex",
  "arrayLast",
  "arrayLastIndex",
  "arrayMap",
  "arrayFilter",
  "arrayExists",
  "arrayAll",
  "arrayReduce",
  "arrayReduceInRanges",
  "arrayFill",
  "arrayReverseFill",

  // Math Functions
  "abs",
  "sign",
  "round",
  "roundToExp2",
  "roundDuration",
  "roundAge",
  "floor",
  "ceil",
  "trunc",
  "sqrt",
  "cbrt",
  "pow",
  "power",
  "exp",
  "exp2",
  "exp10",
  "log",
  "log2",
  "log10",
  "ln",
  "sin",
  "cos",
  "tan",
  "asin",
  "acos",
  "atan",
  "atan2",
  "greatest",
  "least",
  "random",
  "rand",
  "randomFixedString",
  "pi",
  "e",
  "degrees",
  "radians",

  // Type Conversion
  "toString",
  "toFixedString",
  "cast",
  "CAST",
  "accurateCast",
  "accurateCastOrNull",
  "toInt8",
  "toInt16",
  "toInt32",
  "toInt64",
  "toInt128",
  "toInt256",
  "toUInt8",
  "toUInt16",
  "toUInt32",
  "toUInt64",
  "toUInt128",
  "toUInt256",
  "toFloat32",
  "toFloat64",
  "toDecimal32",
  "toDecimal64",
  "toDecimal128",
  "toBool",
  "toStringCutToZero",
  "reinterpretAsString",
  "reinterpretAsFixedString",

  // Conditional Functions
  "if",
  "multiIf",
  "isNull",
  "isNotNull",
  "ifNull",
  "nullIf",
  "assumeNotNull",
  "coalesce",
  "greatest",
  "least",

  // Hash Functions
  "halfMD5",
  "MD4",
  "MD5",
  "SHA1",
  "SHA224",
  "SHA256",
  "SHA512",
  "cityHash64",
  "intHash32",
  "intHash64",
  "sipHash64",
  "sipHash128",

  // URL Functions
  "protocol",
  "domain",
  "domainWithoutWWW",
  "topLevelDomain",
  "firstSignificantSubdomain",
  "cutToFirstSignificantSubdomain",
  "cutURLParameter",
  "cutQueryString",
  "cutFragment",
  "extractURLParameter",
  "extractURLParameterNames",
  "extractURLParameters",
  "path",
  "pathFull",
  "queryString",
  "fragment",
  "queryStringAndFragment",

  // IP Functions
  "IPv4NumToString",
  "IPv4StringToNum",
  "IPv4NumToStringClassC",
  "IPv6NumToString",
  "IPv6StringToNum",
  "isIPv4String",
  "isIPv6String",

  // JSON Functions
  "visitParamHas",
  "visitParamExtractUInt",
  "visitParamExtractInt",
  "visitParamExtractFloat",
  "visitParamExtractBool",
  "visitParamExtractRaw",
  "visitParamExtractString",
  "JSONHas",
  "JSONLength",
  "JSONType",
  "JSONExtractUInt",
  "JSONExtractInt",
  "JSONExtractFloat",
  "JSONExtractBool",
  "JSONExtractString",
  "JSONExtract",
  "JSONExtractKeysAndValues",
  "JSONExtractRaw",
  "JSONExtractArrayRaw",

  // Tuple Functions
  "tuple",
  "tupleElement",
  "untuple",
  "tupleHMac",
  "tupleToNameValuePairs",

  // Map Functions
  "map",
  "mapKeys",
  "mapValues",
  "mapContains",
  "mapAdd",
  "mapSubtract",
];

export const CLICKHOUSE_ENGINES = [
  // MergeTree Family
  "MergeTree",
  "ReplacingMergeTree",
  "SummingMergeTree",
  "AggregatingMergeTree",
  "CollapsingMergeTree",
  "VersionedCollapsingMergeTree",
  "GraphiteMergeTree",

  // Log Family
  "TinyLog",
  "StripeLog",
  "Log",

  // Integration Engines
  "Kafka",
  "RabbitMQ",
  "MySQL",
  "PostgreSQL",
  "ODBC",
  "JDBC",
  "MongoDB",
  "Redis",
  "S3",
  "HDFS",
  "URL",
  "File",
  "SQLite",

  // Special Engines
  "Distributed",
  "MaterializedView",
  "Dictionary",
  "Memory",
  "Set",
  "Join",
  "Buffer",
  "Null",
  "View",
  "LiveView",
];
